# Permalinks
permalink:           pretty

# Setup
title:               'YinYangi'
url:                 https://yinyangi.in
tagline:             'Personal site for devops & developer Sumit Murari'
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sumit Murari
  url:               https://twitter.com/sumitmurari
  email:             murari.sumit@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/bradleytaunt/lightspeed
